package cn.com.xinxin.portal.repository.dao;

import cn.com.xinxin.portal.repository.model.AuditDO;

public interface AuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    int insert(AuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    int insertSelective(AuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    AuditDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuditDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuditDO record);
}