package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.AuthsDO;

import java.util.List;

public interface AuthsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    int insert(AuthsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    int insertSelective(AuthsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    AuthsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auths
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthsDO record);


    List<AuthsDO> selectAllAuths();
}