package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.DepartmentDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DepartmentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int insert(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int insertSelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    DepartmentDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DepartmentDO record);

    /**
     * 通过机构id查询部门列表
     * @param tenantId 机构id
     * @return 部门列表
     */
    List<DepartmentDO> selectByOrgId(@Param(value = "tenantId") String tenantId);

    /**
     * 批量插入记录
     * @param departmentDOS 部门信息
     * @return 插入成功条数
     */
    int insertBatch(@Param(value = "departmentDOS")List<DepartmentDO> departmentDOS);

    /**
     * 批量更新记录
     * @param departmentDOS 部门信息
     * @return 更新成功条数
     */
    int updateBatchById(@Param(value = "departmentDOS")List<DepartmentDO> departmentDOS);


    /**
     * 查询所有的部门
     * @return
     */
    List<DepartmentDO> listAllWechatDepts();


    /**
     * @param deptId
     * @return
     */
    DepartmentDO selectByDeptId(@Param("deptId") String deptId);

    /**
     *
     * @param deptId
     * @param deptName
     * @param deptEngName
     * @return
     */
    List<DepartmentDO>  queryDeptsByNameOrId(@Param("deptId") String deptId,
                                             @Param("deptName") String deptName,
                                             @Param("deptEngName") String deptEngName);


    /**
     *
     * @param deptIds
     * @return
     */
    List<String> selectSubDeptsByDeptId(@Param("deptIds") List<String> deptIds);

    /**
     * 将记录状态置为失效
     * @param tenantId 租户id
     * @param taskId 任务流水
     * @return 成功更新的条数
     */
    int updateInactiveStatus(@Param(value = "tenantId") String tenantId, @Param(value = "taskId") String taskId);
}