package cn.com.xinxin.sass.repository.dao;

/*
 *
 * Copyright 2020 www.xinxindigits.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"),to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Redistribution and selling copies of the software are prohibited, only if the authorization from xinxin digits
 * was obtained.Neither the name of the xinxin digits; nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written permission.
 *
 */

import cn.com.xinxin.sass.repository.model.GroupChatDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupChatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    int insert(GroupChatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    int insertSelective(GroupChatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    GroupChatDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupChatDO record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_chat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupChatDO record);

    /**
     * 通过群聊id查询群信息
     * @param chatIdS 群id
     * @return 群信息
     */
    List<GroupChatDO> selectByChatIdS(@Param(value = "chatIdS") List<String> chatIdS);

    /**
     * 批量插入记录
     * @param groupChatDOS 记录
     * @return 成功插入记录的条数
     */
    int insertBatch(@Param(value = "groupChatDOS") List<GroupChatDO> groupChatDOS);

    /**
     * 批量更新记录
     * @param groupChatDOS 记录
     * @return 成功更新记录的条数
     */
    int updateBatch(@Param(value = "groupChatDOS") List<GroupChatDO> groupChatDOS);

    /**
     * 通过chatId查询记录
     * @param chatId 群id
     * @return 记录
     */
    GroupChatDO selectByChatId(@Param(value = "chatId") String chatId);
}