package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.MemberReceivedDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemberReceivedDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    int insert(MemberReceivedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    int insertSelective(MemberReceivedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    MemberReceivedDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberReceivedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_received
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberReceivedDO record);

    /**
     * 批量插入记录
     * @param memberReceivedDOS 记录
     * @return 插入成功条数
     */
    int insertBatch(@Param(value = "memberReceivedDOS") List<MemberReceivedDO> memberReceivedDOS);


    /**
     * 通过takId和orgId和部门id查询记录
     * @param taskId 任务id
     * @param tenantId 机构id
     * @param departmentId 部门id
     * @return 部门暂存信息
     */
    List<MemberReceivedDO> queryByTaskIdAndOrgIdAndDepartmentId(@Param(value = "taskId") String taskId,
                                                                @Param(value = "tenantId") String tenantId,
                                                                @Param(value = "departmentId") String departmentId);
}