package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.MemberDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemberDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    int insert(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    int insertSelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    MemberDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberDO record);

    /**
     * 通过机构id和用户id查询记录
     * @param tenantId 机构id
     * @param userIdS 用户id
     * @return 成员列表
     */
    List<MemberDO> queryByOrgIdAndUserId(@Param(value = "tenantId") String tenantId,
                                         @Param(value = "userIdS") List<String> userIdS);

    /**
     * 批量插入
     * @param memberDOS 成员列表
     * @return 插入成功数量
     */
    int insertBatch(@Param(value = "memberDOS") List<MemberDO> memberDOS);

    /**
     * 批量更新
     * @param memberDOS 成员列表
     * @return 更新成功数量
     */
    int updateBatchById(@Param(value = "memberDOS") List<MemberDO> memberDOS);


    /**
     *
     * @param deptId
     * @return
     */
    List<MemberDO> queryDeptId(@Param("deptId") String deptId);

    /**
     *
     * @return
     */
    List<MemberDO> queryAllMembersByPage();


    /**
     * @param deptIds
     * @return
     */
    List<MemberDO> queryDeptIdList(@Param("deptIds") List<String> deptIds);


    /**
     *
     * @param memberName
     * @param mobile
     * @return
     */
    List<MemberDO> queryByNameAndMobile(@Param("memberName")String memberName,
                                        @Param("mobile") String mobile);

    /**
     * 将记录状态置为失效
     * @param tenantId 租户id
     * @param taskId 任务流水
     * @return 成功更新的条数
     */
    int updateInactiveStatus(@Param(value = "tenantId") String tenantId, @Param(value = "taskId") String taskId);


    /**
     *
     * @param userId
     * @return
     */
    MemberDO queryByUserId(@Param("userId")String userId);


}