package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.MsgRecordDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MsgRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    int insert(MsgRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    int insertSelective(MsgRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    MsgRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MsgRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MsgRecordDO record);

    /**
     * 批量插入记录
     * @param msgRecordDOS 消息记录
     * @return 插入记录条数
     */
    int insertBatch(@Param(value = "msgRecordDOS") List<MsgRecordDO> msgRecordDOS);
}