package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.OplogDO;
import cn.com.xinxin.sass.repository.model.OplogDOWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OplogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int insert(OplogDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int insertSelective(OplogDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    OplogDOWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OplogDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OplogDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oplog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OplogDO record);

    /**
     * 查询某个账户的操作
     * @param account
     * @return
     */
    List<OplogDOWithBLOBs> selectOplogsByAccount(@Param("account") String account);


}