package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.OrgDataSyncExcpDO;

public interface OrgDataSyncExcpDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int insert(OrgDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int insertSelective(OrgDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    OrgDataSyncExcpDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrgDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrgDataSyncExcpDO record);
}