package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.OrgDataSyncLogDO;

public interface OrgDataSyncLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insert(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insertSelective(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    OrgDataSyncLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrgDataSyncLogDO record);
}