package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.OrgDataSyncConfigDO;

public interface OrgDataSyncConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    int insert(OrgDataSyncConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    int insertSelective(OrgDataSyncConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    OrgDataSyncConfigDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrgDataSyncConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrgDataSyncConfigDO record);
}