package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.OrgDataSyncLogDO;
import org.apache.ibatis.annotations.Param;

public interface OrgDataSyncLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insert(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insertSelective(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    OrgDataSyncLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrgDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrgDataSyncLogDO record);

    /**
     * 插入记录并将生成的id保存到orgDataSyncLogDO的id字段
     * @param orgDataSyncLogDO 机构同步任务日志
     * @return 插入记录成功的条数
     */
    int insertReturnId(@Param(value = "orgDataSyncLogDO") OrgDataSyncLogDO orgDataSyncLogDO);
}