package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.ResourceDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    int insert(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    int insertSelective(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    ResourceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceDO record);


    List<ResourceDO> findResources(List<String> codes);

    List<ResourceDO> findResourcesByIds(List<Long> ids);

    List<ResourceDO> findChildMenuByParentId(@Param("parentId") Long parentId);

    List<ResourceDO> findRootResources();

    List<ResourceDO> findAllResources();

    List<ResourceDO> findByCondition(ResourceDO condition);

    List<ResourceDO> findChildrenByParentIds(List<Long> parentIds);

    List<Long> findResourceIds(List<String> codes);

    ResourceDO findByResourceCode(String code);
}