package cn.com.xinxin.sass.repository.dao;

/*
 *
 * Copyright 2020 www.xinxindigits.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"),to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Redistribution and selling copies of the software are prohibited, only if the authorization from xinxin digits
 * was obtained.Neither the name of the xinxin digits; nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written permission.
 *
 */

import cn.com.xinxin.sass.repository.model.ResourceDO;
import cn.com.xinxin.sass.repository.model.RoleResourceDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    int insert(RoleResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    int insertSelective(RoleResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    RoleResourceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleResourceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleResourceDO record);

    /**
     *
     * @param roleCode
     * @return
     */
    List<ResourceDO> findResourceByRoleCode(@Param("roleCode") String roleCode);

    /**
     *
     * @param roleCodes
     * @return
     */
    List<ResourceDO> findResources(List<String> roleCodes);

    /**
     *
     * @param list
     * @return
     */
    int batchInsert(List<RoleResourceDO> list);

    /**
     *
     * @param condition
     * @return
     */
    List<RoleResourceDO> findByCondition(RoleResourceDO condition);

    /**
     *
     * @param roleCode
     * @param resourceCodes
     * @return
     */
    int delete(@Param("roleCode") String roleCode,@Param("list")List<String> resourceCodes);

    /**
     *
     * @param rsCode
     * @return
     */
    List<RoleResourceDO> queryRolesAndResourcesByRSCode(@Param("rsCode") String rsCode);


    /**
     *
     * @param rsCodeList
     * @return
     */
    List<RoleResourceDO> queryRolesAndResourcesByRSCodeList(@Param("rsCodeList") List<String> rsCodeList);


    /**
     *
     * @param roleResourceDO
     * @return
     */
    int updateByRoleCode(RoleResourceDO roleResourceDO);

    /**
     *
     * @param roleResourceDO
     * @return
     */
    int updateByResourceCode(RoleResourceDO roleResourceDO);

    /**
     *
     * @param roleCode
     * @return
     */
    int deleteByRoleCodes(@Param("roleCodes") List<String> roleCode);
}