package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.RoleDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int insert(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int insertSelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    RoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleDO record);

    List<RoleDO> findRoles(List<Long> roleIds);

    List<RoleDO> findByCondition(RoleDO condition);

    RoleDO findByRoleCode(String code);

    int updateByCodeSelective(RoleDO record);

    int deleteByCodes(@Param("roleCodes") List<String> roleCodes);

    /**
     *
     * @param roleCodes
     * @return
     */
    List<RoleDO> findRolesByCodes(@Param("roleCodes") List<String> roleCodes);

}