package cn.com.xinxin.sass.repository.dao;

/*
 *
 * Copyright 2020 www.xinxindigits.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"),to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Redistribution and selling copies of the software are prohibited, only if the authorization from xinxin digits
 * was obtained.Neither the name of the xinxin digits; nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written permission.
 *
 */

import cn.com.xinxin.sass.repository.model.TagsDO;
import cn.com.xinxin.sass.repository.model.TagsMapDO;
import cn.com.xinxin.sass.repository.model.TagsRelationsDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TagsRelationsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    int insert(TagsRelationsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    int insertSelective(TagsRelationsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    TagsRelationsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TagsRelationsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags_relations
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TagsRelationsDO record);

    /**
     * 删除tagid对应的映射关系
     * @param tagId
     * @return
     */
    int deleteTagsRelationsByTagId(@Param("tagId") Long tagId);


    /**
     * @param relationsList
     * @return
     */
    int batchCreateRelations(@Param("relationsList")List<TagsRelationsDO> relationsList);


    /**
     * 查询某个key的tag映射关系
     * @param keyId
     * @return
     */
    List<TagsDO> selectTagsByKeyId(@Param("keyId")String keyId);

    /**
     * key ids
     * @param keyIds
     * @return
     */
    List<TagsDO> selectTagsByKeyIdLists(@Param("keyIdList")List<String> keyIds);

    /**
     * key ids
     * @param keyIds
     * @return
     */
    List<TagsMapDO> selectTagsMapsByKeyIds(@Param("keyIdList") List<String> keyIds);


    /**
     * 删除标签
     * @param keyId
     * @return
     */
    int deleteTagsBykeyId(@Param("keyId") String keyId);
}