package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.TenantDataSyncLogDO;
import org.apache.ibatis.annotations.Param;

public interface TenantDataSyncLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insert(TenantDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int insertSelective(TenantDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    TenantDataSyncLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TenantDataSyncLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TenantDataSyncLogDO record);

    /**
     * 插入记录并将生成的id保存到orgDataSyncLogDO的id字段
     * @param tenantDataSyncLogDO 机构同步任务日志
     * @return 插入记录成功的条数
     */
    int insertReturnId(@Param(value = "tenantDataSyncLogDO") TenantDataSyncLogDO tenantDataSyncLogDO);
}