package cn.com.xinxin.sass.repository.dao;

import cn.com.xinxin.sass.repository.model.TenantDataSyncExcpDO;

public interface TenantDataSyncExcpDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int insert(TenantDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int insertSelective(TenantDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    TenantDataSyncExcpDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TenantDataSyncExcpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_data_sync_excp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TenantDataSyncExcpDO record);
}