package cn.com.xinxin.sass.repository.dao;

/*
 *
 * Copyright 2020 www.xinxindigits.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"),to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Redistribution and selling copies of the software are prohibited, only if the authorization from xinxin digits
 * was obtained.Neither the name of the xinxin digits; nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written permission.
 *
 */

import cn.com.xinxin.sass.repository.model.UserOrgDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserOrgDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    int insert(UserOrgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    int insertSelective(UserOrgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    UserOrgDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserOrgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserOrgDO record);

    /**
     * 查询接口
     * @param account
     * @return
     */
    List<UserOrgDO> queryUserOrgsByAccount(@Param("account") String account);


    /**
     * 删除
     * @param account
     * @return
     */
    int removeUserOrgRelationByAccount(@Param("account") String account);

    /**
     * 删除接口
     * @param orgCode
     * @return
     */
    int removeUserOrgRelationByOrgCode(@Param("orgCode")String orgCode);

    /**
     * 批量查询
     * @param lists
     * @return
     */
    int insertByBatch(@Param("lists") List<UserOrgDO> lists);

    /**
     * 删除
     * @param accounts
     * @return
     */
    int removeUserOrgRelationByAccountList(@Param("accounts") List<String> accounts);


    /**
     * 查询
     * @param accounts
     * @return
     */
    List<UserOrgDO> queryUserOrgsByAccountList(@Param("accounts") List<String> accounts);

    /**
     *
     * @param orgCode
     * @return
     */
    List<UserOrgDO> queryUserOrgsByOrgCode(@Param("orgCode")String orgCode);


    /**
     *
     * @param orgCodeList
     * @return
     */
    List<UserOrgDO> queryUserOrgsByOrgCodeLists(@Param("orgCodeList")List<String> orgCodeList);
}