package cn.com.xinxin.sass.repository.model;

import java.util.Date;

public class AuditDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.audit_usr_account
     *
     * @mbg.generated
     */
    private String auditUsrAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.audit_usr_name
     *
     * @mbg.generated
     */
    private String auditUsrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.biz_type
     *
     * @mbg.generated
     */
    private Byte bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.biz_name
     *
     * @mbg.generated
     */
    private String bizName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.audit_time
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.request_class
     *
     * @mbg.generated
     */
    private String requestClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.request_info
     *
     * @mbg.generated
     */
    private String requestInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.gmt_updated
     *
     * @mbg.generated
     */
    private Date gmtUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.gmt_creator
     *
     * @mbg.generated
     */
    private String gmtCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.gmt_updater
     *
     * @mbg.generated
     */
    private String gmtUpdater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.id
     *
     * @return the value of audit.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.id
     *
     * @param id the value for audit.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.audit_usr_account
     *
     * @return the value of audit.audit_usr_account
     *
     * @mbg.generated
     */
    public String getAuditUsrAccount() {
        return auditUsrAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.audit_usr_account
     *
     * @param auditUsrAccount the value for audit.audit_usr_account
     *
     * @mbg.generated
     */
    public void setAuditUsrAccount(String auditUsrAccount) {
        this.auditUsrAccount = auditUsrAccount == null ? null : auditUsrAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.audit_usr_name
     *
     * @return the value of audit.audit_usr_name
     *
     * @mbg.generated
     */
    public String getAuditUsrName() {
        return auditUsrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.audit_usr_name
     *
     * @param auditUsrName the value for audit.audit_usr_name
     *
     * @mbg.generated
     */
    public void setAuditUsrName(String auditUsrName) {
        this.auditUsrName = auditUsrName == null ? null : auditUsrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.biz_type
     *
     * @return the value of audit.biz_type
     *
     * @mbg.generated
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.biz_type
     *
     * @param bizType the value for audit.biz_type
     *
     * @mbg.generated
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.biz_name
     *
     * @return the value of audit.biz_name
     *
     * @mbg.generated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.biz_name
     *
     * @param bizName the value for audit.biz_name
     *
     * @mbg.generated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.audit_time
     *
     * @return the value of audit.audit_time
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.audit_time
     *
     * @param auditTime the value for audit.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.request_class
     *
     * @return the value of audit.request_class
     *
     * @mbg.generated
     */
    public String getRequestClass() {
        return requestClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.request_class
     *
     * @param requestClass the value for audit.request_class
     *
     * @mbg.generated
     */
    public void setRequestClass(String requestClass) {
        this.requestClass = requestClass == null ? null : requestClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.request_info
     *
     * @return the value of audit.request_info
     *
     * @mbg.generated
     */
    public String getRequestInfo() {
        return requestInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.request_info
     *
     * @param requestInfo the value for audit.request_info
     *
     * @mbg.generated
     */
    public void setRequestInfo(String requestInfo) {
        this.requestInfo = requestInfo == null ? null : requestInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.remark
     *
     * @return the value of audit.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.remark
     *
     * @param remark the value for audit.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.state
     *
     * @return the value of audit.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.state
     *
     * @param state the value for audit.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.gmt_created
     *
     * @return the value of audit.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.gmt_created
     *
     * @param gmtCreated the value for audit.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.gmt_updated
     *
     * @return the value of audit.gmt_updated
     *
     * @mbg.generated
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.gmt_updated
     *
     * @param gmtUpdated the value for audit.gmt_updated
     *
     * @mbg.generated
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.gmt_creator
     *
     * @return the value of audit.gmt_creator
     *
     * @mbg.generated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.gmt_creator
     *
     * @param gmtCreator the value for audit.gmt_creator
     *
     * @mbg.generated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.gmt_updater
     *
     * @return the value of audit.gmt_updater
     *
     * @mbg.generated
     */
    public String getGmtUpdater() {
        return gmtUpdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.gmt_updater
     *
     * @param gmtUpdater the value for audit.gmt_updater
     *
     * @mbg.generated
     */
    public void setGmtUpdater(String gmtUpdater) {
        this.gmtUpdater = gmtUpdater == null ? null : gmtUpdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.extension
     *
     * @return the value of audit.extension
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.extension
     *
     * @param extension the value for audit.extension
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit.deleted
     *
     * @return the value of audit.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit.deleted
     *
     * @param deleted the value for audit.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}