package cn.com.xinxin.sass.repository.model;

import java.util.Date;

public class MemberReceivedDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.department_id_list
     *
     * @mbg.generated
     */
    private String departmentIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.order_list
     *
     * @mbg.generated
     */
    private String orderList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.is_leader_in_dept
     *
     * @mbg.generated
     */
    private String isLeaderInDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.thumb_avatar
     *
     * @mbg.generated
     */
    private String thumbAvatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.ext_attr
     *
     * @mbg.generated
     */
    private String extAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.qr_code
     *
     * @mbg.generated
     */
    private String qrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.external_profile
     *
     * @mbg.generated
     */
    private String externalProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.external_position
     *
     * @mbg.generated
     */
    private String externalPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.hide_mobile
     *
     * @mbg.generated
     */
    private Integer hideMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.english_name
     *
     * @mbg.generated
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.open_userid
     *
     * @mbg.generated
     */
    private String openUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.main_department
     *
     * @mbg.generated
     */
    private Long mainDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.gmt_creator
     *
     * @mbg.generated
     */
    private String gmtCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.gmt_updated
     *
     * @mbg.generated
     */
    private Date gmtUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.gmt_updater
     *
     * @mbg.generated
     */
    private String gmtUpdater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_received.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.id
     *
     * @return the value of member_received.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.id
     *
     * @param id the value for member_received.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.task_id
     *
     * @return the value of member_received.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.task_id
     *
     * @param taskId the value for member_received.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.org_id
     *
     * @return the value of member_received.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.org_id
     *
     * @param orgId the value for member_received.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.user_id
     *
     * @return the value of member_received.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.user_id
     *
     * @param userId the value for member_received.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.name
     *
     * @return the value of member_received.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.name
     *
     * @param name the value for member_received.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.mobile
     *
     * @return the value of member_received.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.mobile
     *
     * @param mobile the value for member_received.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.department_id_list
     *
     * @return the value of member_received.department_id_list
     *
     * @mbg.generated
     */
    public String getDepartmentIdList() {
        return departmentIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.department_id_list
     *
     * @param departmentIdList the value for member_received.department_id_list
     *
     * @mbg.generated
     */
    public void setDepartmentIdList(String departmentIdList) {
        this.departmentIdList = departmentIdList == null ? null : departmentIdList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.order_list
     *
     * @return the value of member_received.order_list
     *
     * @mbg.generated
     */
    public String getOrderList() {
        return orderList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.order_list
     *
     * @param orderList the value for member_received.order_list
     *
     * @mbg.generated
     */
    public void setOrderList(String orderList) {
        this.orderList = orderList == null ? null : orderList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.position
     *
     * @return the value of member_received.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.position
     *
     * @param position the value for member_received.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.gender
     *
     * @return the value of member_received.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.gender
     *
     * @param gender the value for member_received.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.mail
     *
     * @return the value of member_received.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.mail
     *
     * @param mail the value for member_received.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.is_leader_in_dept
     *
     * @return the value of member_received.is_leader_in_dept
     *
     * @mbg.generated
     */
    public String getIsLeaderInDept() {
        return isLeaderInDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.is_leader_in_dept
     *
     * @param isLeaderInDept the value for member_received.is_leader_in_dept
     *
     * @mbg.generated
     */
    public void setIsLeaderInDept(String isLeaderInDept) {
        this.isLeaderInDept = isLeaderInDept == null ? null : isLeaderInDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.avatar
     *
     * @return the value of member_received.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.avatar
     *
     * @param avatar the value for member_received.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.thumb_avatar
     *
     * @return the value of member_received.thumb_avatar
     *
     * @mbg.generated
     */
    public String getThumbAvatar() {
        return thumbAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.thumb_avatar
     *
     * @param thumbAvatar the value for member_received.thumb_avatar
     *
     * @mbg.generated
     */
    public void setThumbAvatar(String thumbAvatar) {
        this.thumbAvatar = thumbAvatar == null ? null : thumbAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.telephone
     *
     * @return the value of member_received.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.telephone
     *
     * @param telephone the value for member_received.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.alias
     *
     * @return the value of member_received.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.alias
     *
     * @param alias the value for member_received.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.status
     *
     * @return the value of member_received.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.status
     *
     * @param status the value for member_received.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.ext_attr
     *
     * @return the value of member_received.ext_attr
     *
     * @mbg.generated
     */
    public String getExtAttr() {
        return extAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.ext_attr
     *
     * @param extAttr the value for member_received.ext_attr
     *
     * @mbg.generated
     */
    public void setExtAttr(String extAttr) {
        this.extAttr = extAttr == null ? null : extAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.qr_code
     *
     * @return the value of member_received.qr_code
     *
     * @mbg.generated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.qr_code
     *
     * @param qrCode the value for member_received.qr_code
     *
     * @mbg.generated
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.external_profile
     *
     * @return the value of member_received.external_profile
     *
     * @mbg.generated
     */
    public String getExternalProfile() {
        return externalProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.external_profile
     *
     * @param externalProfile the value for member_received.external_profile
     *
     * @mbg.generated
     */
    public void setExternalProfile(String externalProfile) {
        this.externalProfile = externalProfile == null ? null : externalProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.external_position
     *
     * @return the value of member_received.external_position
     *
     * @mbg.generated
     */
    public String getExternalPosition() {
        return externalPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.external_position
     *
     * @param externalPosition the value for member_received.external_position
     *
     * @mbg.generated
     */
    public void setExternalPosition(String externalPosition) {
        this.externalPosition = externalPosition == null ? null : externalPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.address
     *
     * @return the value of member_received.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.address
     *
     * @param address the value for member_received.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.hide_mobile
     *
     * @return the value of member_received.hide_mobile
     *
     * @mbg.generated
     */
    public Integer getHideMobile() {
        return hideMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.hide_mobile
     *
     * @param hideMobile the value for member_received.hide_mobile
     *
     * @mbg.generated
     */
    public void setHideMobile(Integer hideMobile) {
        this.hideMobile = hideMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.english_name
     *
     * @return the value of member_received.english_name
     *
     * @mbg.generated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.english_name
     *
     * @param englishName the value for member_received.english_name
     *
     * @mbg.generated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.open_userid
     *
     * @return the value of member_received.open_userid
     *
     * @mbg.generated
     */
    public String getOpenUserid() {
        return openUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.open_userid
     *
     * @param openUserid the value for member_received.open_userid
     *
     * @mbg.generated
     */
    public void setOpenUserid(String openUserid) {
        this.openUserid = openUserid == null ? null : openUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.main_department
     *
     * @return the value of member_received.main_department
     *
     * @mbg.generated
     */
    public Long getMainDepartment() {
        return mainDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.main_department
     *
     * @param mainDepartment the value for member_received.main_department
     *
     * @mbg.generated
     */
    public void setMainDepartment(Long mainDepartment) {
        this.mainDepartment = mainDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.extension
     *
     * @return the value of member_received.extension
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.extension
     *
     * @param extension the value for member_received.extension
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.gmt_created
     *
     * @return the value of member_received.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.gmt_created
     *
     * @param gmtCreated the value for member_received.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.gmt_creator
     *
     * @return the value of member_received.gmt_creator
     *
     * @mbg.generated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.gmt_creator
     *
     * @param gmtCreator the value for member_received.gmt_creator
     *
     * @mbg.generated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.gmt_updated
     *
     * @return the value of member_received.gmt_updated
     *
     * @mbg.generated
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.gmt_updated
     *
     * @param gmtUpdated the value for member_received.gmt_updated
     *
     * @mbg.generated
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.gmt_updater
     *
     * @return the value of member_received.gmt_updater
     *
     * @mbg.generated
     */
    public String getGmtUpdater() {
        return gmtUpdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.gmt_updater
     *
     * @param gmtUpdater the value for member_received.gmt_updater
     *
     * @mbg.generated
     */
    public void setGmtUpdater(String gmtUpdater) {
        this.gmtUpdater = gmtUpdater == null ? null : gmtUpdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_received.deleted
     *
     * @return the value of member_received.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_received.deleted
     *
     * @param deleted the value for member_received.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}