package cn.com.xinxin.sass.repository.model;

public class OplogDOWithBLOBs extends OplogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oplog.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.params
     *
     * @return the value of oplog.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.params
     *
     * @param params the value for oplog.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oplog.result
     *
     * @return the value of oplog.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oplog.result
     *
     * @param result the value for oplog.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}