package cn.com.xinxin.sass.repository.model;

import java.util.Date;

public class OrgBaseInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.corp_id
     *
     * @mbg.generated
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.address_list_secret
     *
     * @mbg.generated
     */
    private String addressListSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.customer_contact_secret
     *
     * @mbg.generated
     */
    private String customerContactSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.private_key
     *
     * @mbg.generated
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.gmt_creator
     *
     * @mbg.generated
     */
    private String gmtCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.gmt_updated
     *
     * @mbg.generated
     */
    private Date gmtUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.gmt_updater
     *
     * @mbg.generated
     */
    private String gmtUpdater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_base_info.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.id
     *
     * @return the value of org_base_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.id
     *
     * @param id the value for org_base_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.org_id
     *
     * @return the value of org_base_info.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.org_id
     *
     * @param orgId the value for org_base_info.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.org_name
     *
     * @return the value of org_base_info.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.org_name
     *
     * @param orgName the value for org_base_info.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.corp_id
     *
     * @return the value of org_base_info.corp_id
     *
     * @mbg.generated
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.corp_id
     *
     * @param corpId the value for org_base_info.corp_id
     *
     * @mbg.generated
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.address_list_secret
     *
     * @return the value of org_base_info.address_list_secret
     *
     * @mbg.generated
     */
    public String getAddressListSecret() {
        return addressListSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.address_list_secret
     *
     * @param addressListSecret the value for org_base_info.address_list_secret
     *
     * @mbg.generated
     */
    public void setAddressListSecret(String addressListSecret) {
        this.addressListSecret = addressListSecret == null ? null : addressListSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.customer_contact_secret
     *
     * @return the value of org_base_info.customer_contact_secret
     *
     * @mbg.generated
     */
    public String getCustomerContactSecret() {
        return customerContactSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.customer_contact_secret
     *
     * @param customerContactSecret the value for org_base_info.customer_contact_secret
     *
     * @mbg.generated
     */
    public void setCustomerContactSecret(String customerContactSecret) {
        this.customerContactSecret = customerContactSecret == null ? null : customerContactSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.private_key
     *
     * @return the value of org_base_info.private_key
     *
     * @mbg.generated
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.private_key
     *
     * @param privateKey the value for org_base_info.private_key
     *
     * @mbg.generated
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.extension
     *
     * @return the value of org_base_info.extension
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.extension
     *
     * @param extension the value for org_base_info.extension
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.gmt_created
     *
     * @return the value of org_base_info.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.gmt_created
     *
     * @param gmtCreated the value for org_base_info.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.gmt_creator
     *
     * @return the value of org_base_info.gmt_creator
     *
     * @mbg.generated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.gmt_creator
     *
     * @param gmtCreator the value for org_base_info.gmt_creator
     *
     * @mbg.generated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.gmt_updated
     *
     * @return the value of org_base_info.gmt_updated
     *
     * @mbg.generated
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.gmt_updated
     *
     * @param gmtUpdated the value for org_base_info.gmt_updated
     *
     * @mbg.generated
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.gmt_updater
     *
     * @return the value of org_base_info.gmt_updater
     *
     * @mbg.generated
     */
    public String getGmtUpdater() {
        return gmtUpdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.gmt_updater
     *
     * @param gmtUpdater the value for org_base_info.gmt_updater
     *
     * @mbg.generated
     */
    public void setGmtUpdater(String gmtUpdater) {
        this.gmtUpdater = gmtUpdater == null ? null : gmtUpdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_base_info.deleted
     *
     * @return the value of org_base_info.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_base_info.deleted
     *
     * @param deleted the value for org_base_info.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}