package cn.com.xinxin.sass.repository.model;

/*
 *
 * Copyright 2020 www.xinxindigits.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"),to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice
 * shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Redistribution and selling copies of the software are prohibited, only if the authorization from xinxin digits
 * was obtained.Neither the name of the xinxin digits; nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written permission.
 *
 */

import java.util.Date;

public class TenantDataSyncExcpDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_id
     *
     * @mbg.generated
     */
    private String excpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.task_id
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.org_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.task_type
     *
     * @mbg.generated
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_step
     *
     * @mbg.generated
     */
    private String excpStep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_msg_start_seq
     *
     * @mbg.generated
     */
    private Long excpMsgStartSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_msg_end_seq
     *
     * @mbg.generated
     */
    private Long excpMsgEndSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_department_id
     *
     * @mbg.generated
     */
    private Long excpDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_code
     *
     * @mbg.generated
     */
    private String excpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.excp_desc
     *
     * @mbg.generated
     */
    private String excpDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.extension
     *
     * @mbg.generated
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.gmt_created
     *
     * @mbg.generated
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.gmt_creator
     *
     * @mbg.generated
     */
    private String gmtCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.gmt_updated
     *
     * @mbg.generated
     */
    private Date gmtUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.gmt_updater
     *
     * @mbg.generated
     */
    private String gmtUpdater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_data_sync_excp.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.id
     *
     * @return the value of org_data_sync_excp.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.id
     *
     * @param id the value for org_data_sync_excp.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_id
     *
     * @return the value of org_data_sync_excp.excp_id
     *
     * @mbg.generated
     */
    public String getExcpId() {
        return excpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_id
     *
     * @param excpId the value for org_data_sync_excp.excp_id
     *
     * @mbg.generated
     */
    public void setExcpId(String excpId) {
        this.excpId = excpId == null ? null : excpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.task_id
     *
     * @return the value of org_data_sync_excp.task_id
     *
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.task_id
     *
     * @param taskId the value for org_data_sync_excp.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.org_id
     *
     * @return the value of org_data_sync_excp.org_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.org_id
     *
     * @param tenantId the value for org_data_sync_excp.org_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.task_type
     *
     * @return the value of org_data_sync_excp.task_type
     *
     * @mbg.generated
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.task_type
     *
     * @param taskType the value for org_data_sync_excp.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_step
     *
     * @return the value of org_data_sync_excp.excp_step
     *
     * @mbg.generated
     */
    public String getExcpStep() {
        return excpStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_step
     *
     * @param excpStep the value for org_data_sync_excp.excp_step
     *
     * @mbg.generated
     */
    public void setExcpStep(String excpStep) {
        this.excpStep = excpStep == null ? null : excpStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_msg_start_seq
     *
     * @return the value of org_data_sync_excp.excp_msg_start_seq
     *
     * @mbg.generated
     */
    public Long getExcpMsgStartSeq() {
        return excpMsgStartSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_msg_start_seq
     *
     * @param excpMsgStartSeq the value for org_data_sync_excp.excp_msg_start_seq
     *
     * @mbg.generated
     */
    public void setExcpMsgStartSeq(Long excpMsgStartSeq) {
        this.excpMsgStartSeq = excpMsgStartSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_msg_end_seq
     *
     * @return the value of org_data_sync_excp.excp_msg_end_seq
     *
     * @mbg.generated
     */
    public Long getExcpMsgEndSeq() {
        return excpMsgEndSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_msg_end_seq
     *
     * @param excpMsgEndSeq the value for org_data_sync_excp.excp_msg_end_seq
     *
     * @mbg.generated
     */
    public void setExcpMsgEndSeq(Long excpMsgEndSeq) {
        this.excpMsgEndSeq = excpMsgEndSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_department_id
     *
     * @return the value of org_data_sync_excp.excp_department_id
     *
     * @mbg.generated
     */
    public Long getExcpDepartmentId() {
        return excpDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_department_id
     *
     * @param excpDepartmentId the value for org_data_sync_excp.excp_department_id
     *
     * @mbg.generated
     */
    public void setExcpDepartmentId(Long excpDepartmentId) {
        this.excpDepartmentId = excpDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_code
     *
     * @return the value of org_data_sync_excp.excp_code
     *
     * @mbg.generated
     */
    public String getExcpCode() {
        return excpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_code
     *
     * @param excpCode the value for org_data_sync_excp.excp_code
     *
     * @mbg.generated
     */
    public void setExcpCode(String excpCode) {
        this.excpCode = excpCode == null ? null : excpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.excp_desc
     *
     * @return the value of org_data_sync_excp.excp_desc
     *
     * @mbg.generated
     */
    public String getExcpDesc() {
        return excpDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.excp_desc
     *
     * @param excpDesc the value for org_data_sync_excp.excp_desc
     *
     * @mbg.generated
     */
    public void setExcpDesc(String excpDesc) {
        this.excpDesc = excpDesc == null ? null : excpDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.extension
     *
     * @return the value of org_data_sync_excp.extension
     *
     * @mbg.generated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.extension
     *
     * @param extension the value for org_data_sync_excp.extension
     *
     * @mbg.generated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.gmt_created
     *
     * @return the value of org_data_sync_excp.gmt_created
     *
     * @mbg.generated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.gmt_created
     *
     * @param gmtCreated the value for org_data_sync_excp.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.gmt_creator
     *
     * @return the value of org_data_sync_excp.gmt_creator
     *
     * @mbg.generated
     */
    public String getGmtCreator() {
        return gmtCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.gmt_creator
     *
     * @param gmtCreator the value for org_data_sync_excp.gmt_creator
     *
     * @mbg.generated
     */
    public void setGmtCreator(String gmtCreator) {
        this.gmtCreator = gmtCreator == null ? null : gmtCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.gmt_updated
     *
     * @return the value of org_data_sync_excp.gmt_updated
     *
     * @mbg.generated
     */
    public Date getGmtUpdated() {
        return gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.gmt_updated
     *
     * @param gmtUpdated the value for org_data_sync_excp.gmt_updated
     *
     * @mbg.generated
     */
    public void setGmtUpdated(Date gmtUpdated) {
        this.gmtUpdated = gmtUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.gmt_updater
     *
     * @return the value of org_data_sync_excp.gmt_updater
     *
     * @mbg.generated
     */
    public String getGmtUpdater() {
        return gmtUpdater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.gmt_updater
     *
     * @param gmtUpdater the value for org_data_sync_excp.gmt_updater
     *
     * @mbg.generated
     */
    public void setGmtUpdater(String gmtUpdater) {
        this.gmtUpdater = gmtUpdater == null ? null : gmtUpdater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_data_sync_excp.deleted
     *
     * @return the value of org_data_sync_excp.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_data_sync_excp.deleted
     *
     * @param deleted the value for org_data_sync_excp.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}